# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source files
COPY . ./

# Build the application
RUN npm run build

# Expose port if needed
EXPOSE 3000

# Start the MCP server
CMD ["node", "build/app.js"]
